# -*- coding: utf-8 -*-
"""SendingMail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaFrz1TjdCqmPYKrvXU6OO3ON_UxdlwI
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# 이메일 발송 정보 설정
smtp_server = "smtp.gmail.com"            # Gmail SMTP 서버 주소
smtp_port = 587                           # Gmail SMTP 포트 번호
sender_email = "junghyun6555@gmail.com"   # 보내는 사람 이메일
sender_password = "invg xbzj yjgq hgju"   # 16자리 앱 비밀번호
receiver_email = "ymkim@hyscape.co.kr"    # 받는 사람 이메일

# 이메일 본문 생성
msg = MIMEMultipart()
msg['From'] = sender_email
msg['To'] = receiver_email
msg['Subject'] = "[TEST] 프로토타입 ver.1"

# 이메일 본문 내용 작성 (HTML 형식)
body = """
<html>
<body>
    <h2>안녕하세요.</h2>
    <p>이 메일은 자동으로 발송되는 테스트 이메일입니다.</p>
    <p>감사합니다.</p>
</body>
</html>
"""
msg.attach(MIMEText(body, 'html'))

try:
    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()
    server.login(sender_email, sender_password)
    text = msg.as_string()
    server.sendmail(sender_email, receiver_email, text)
    server.quit()
    print(f"성공적으로 {receiver_email} 주소로 이메일을 발송했습니다.")

except Exception as e:
    print(f"이메일 발송에 실패했습니다: {e}")